# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashinfo',
            old_name='trash_path',
            new_name='trash_config',
        ),
    ]
