# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0003_auto_20170608_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_config_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_path',
            field=models.CharField(max_length=500),
        ),
    ]
