# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0005_auto_20170608_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashinfo',
            name='trash_config_path',
        ),
    ]
