# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0006_remove_trashinfo_trash_config_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashinfo',
            name='trash_name',
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='config_path',
            field=models.CharField(default='/home/sergey/.smrmconfig.json', max_length=500),
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_path',
            field=models.CharField(max_length=200),
        ),
    ]
