# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0007_auto_20170613_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default=' ', max_length=500)),
                ('silent', models.BooleanField(default=False)),
                ('dry', models.BooleanField(default=False)),
                ('force', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='file_storage_time',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='recover_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='trash_maximum_size',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
