# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0008_auto_20170622_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='trash',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TrashExplorer.TrashInfo'),
        ),
    ]
