# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0008_auto_20170621_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashinfo',
            name='recover_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
