# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0009_taskinfo_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='operation_type',
            field=models.CharField(choices=[('regex', 'regex'), ('simple_delete', 'simple_delete')], default=None, max_length=50),
        ),
    ]
