# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0010_taskinfo_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='operation_type',
            field=models.CharField(choices=[('regex', 'regex'), ('simple delete', 'simple delete')], default=None, max_length=50),
        ),
    ]
