# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0011_auto_20170623_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='operation_type',
            field=models.CharField(choices=[(1, 'simple delete'), (2, 'delete by regex')], default=None, max_length=50),
        ),
    ]
