# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0013_auto_20170623_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='info_message',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
