# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0014_auto_20170623_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='regex',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
