# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0017_remove_taskinfo_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='operation_type',
            field=models.CharField(choices=[('simple delete', 'simple delete'), ('delete by regex', 'delete by regex')], default=' ', max_length=50),
        ),
    ]
