# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0021_taskinfo_regex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashinfo',
            name='recover_conflict',
        ),
    ]
