# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0024_auto_20170624_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='rename_when_name_conflict',
            field=models.BooleanField(default=True),
        ),
    ]
