# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0025_taskinfo_rename_when_name_conflict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashinfo',
            name='dry',
        ),
        migrations.RemoveField(
            model_name='trashinfo',
            name='force',
        ),
        migrations.RemoveField(
            model_name='trashinfo',
            name='silent',
        ),
    ]
