# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0026_auto_20170624_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='rename_when_name_conflict',
        ),
    ]
