# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0028_auto_20170624_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='log_path',
            field=models.CharField(default='/home/sergey/smrm.log', max_length=500),
        ),
    ]
