# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0029_taskinfo_log_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashinfo',
            old_name='rename_when_name_conflict',
            new_name='rename_when_nameconflict',
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_maximum_size',
            field=models.IntegerField(default=20000),
        ),
    ]
