# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0032_auto_20170624_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='dry',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='force',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='silent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='target',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='trash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrashExplorer.TrashInfo'),
        ),
    ]
