# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0034_auto_20170821_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='file_storage_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='log_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='regex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='trash_maximum_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
