# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0036_auto_20170828_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='verbose',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='silent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='verbose',
            field=models.BooleanField(default=True),
        ),
    ]
