# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0037_auto_20170903_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='dry',
            new_name='dry_run',
        ),
        migrations.AddField(
            model_name='trashinfo',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
    ]
