# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0038_auto_20170903_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='target',
            field=models.TextField(max_length=500),
        ),
    ]
