# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0039_auto_20170904_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='target',
            field=models.TextField(),
        ),
    ]
