# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0040_auto_20170904_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='target',
            field=models.TextField(help_text='100 characters max.'),
        ),
    ]
