# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0045_remove_trashinfo_verbose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='done',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='taskinfo',
            name='force',
        ),
        migrations.RemoveField(
            model_name='taskinfo',
            name='verbose',
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_maximum_size',
            field=models.IntegerField(default=200000),
        ),
    ]
