# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0046_auto_20170915_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='trash_maximum_size',
            field=models.IntegerField(blank=True, help_text='set -1 to off', null=True),
        ),
    ]
