# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 23:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrashExplorer', '0048_auto_20170916_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='trash_maximum_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trashinfo',
            name='trash_maximum_size',
            field=models.IntegerField(default=200000, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
